# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM --platform=${BUILDPLATFORM} d-p00654-b6-p17.jf.intel.com:5000/base-rhel9-4.18
WORKDIR /

COPY redhat.repo /etc/yum.repos.d/
