FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
COPY . .
RUN mkdir -p /workspace/bin && \
    GOMAXPROCS=2 CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
    go build -o /workspace/bin/nri.${TARGETARCH} ./cmd/nri/networkresourcesinjector.go

FROM gcr.io/distroless/static-debian12:nonroot@sha256:a9329520abc449e3b14d5bc3a6ffae065bdde0f02667fa10880c49b35c109fd1
ARG TARGETARCH
WORKDIR /
COPY --from=builder /workspace/bin/nri.${TARGETARCH} /webhook
ENTRYPOINT ["/webhook"]
