FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.24-bookworm@sha256:1a6d4452c65dea36aac2e2d606b01b4a029ec90cc1ae53890540ce6173ea77ac AS builder
ARG TARGETOS
ARG TARGETARCH

COPY . /usr/src/dpu-cni
WORKDIR /usr/src/dpu-cni
RUN GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o dpucni ./dpu-cni/dpu-cni.go

FROM gcr.io/distroless/static-debian12:nonroot@sha256:a9329520abc449e3b14d5bc3a6ffae065bdde0f02667fa10880c49b35c109fd1
COPY --from=builder /usr/src/dpu-cni/dpucni /usr/bin/
WORKDIR /
LABEL io.k8s.display-name="DPU-CNI"
