FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.23-openshift-4.19 AS builder
ARG TARGETOS
ARG TARGETARCH

COPY . /usr/src/dpu-cni

WORKDIR /usr/src/dpu-cni
RUN go build -a -o dpucni ./dpu-cni/dpu-cni.go

FROM registry.ci.openshift.org/ocp/4.19:base-rhel9
COPY --from=builder /usr/src/dpu-cni/dpucni /usr/bin/
WORKDIR /

LABEL io.k8s.display-name="DPU-CNI"
