FROM quay.io/sdaniele/builder-4-19 AS builder
ARG TARGETOS
ARG TARGETARCH

COPY . /usr/src/dpu-cni

WORKDIR /usr/src/dpu-cni
RUN go build -o dpucni ./dpu-cni/dpu-cni.go

FROM quay.io/sdaniele/base-4-19
COPY --from=builder /usr/src/dpu-cni/dpucni /usr/bin/
WORKDIR /

LABEL io.k8s.display-name="DPU-CNI"
