//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfig) DeepCopyInto(out *DpuOperatorConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfig.
func (in *DpuOperatorConfig) DeepCopy() *DpuOperatorConfig {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DpuOperatorConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigList) DeepCopyInto(out *DpuOperatorConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DpuOperatorConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigList.
func (in *DpuOperatorConfigList) DeepCopy() *DpuOperatorConfigList {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DpuOperatorConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigSpec) DeepCopyInto(out *DpuOperatorConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigSpec.
func (in *DpuOperatorConfigSpec) DeepCopy() *DpuOperatorConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DpuOperatorConfigStatus) DeepCopyInto(out *DpuOperatorConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DpuOperatorConfigStatus.
func (in *DpuOperatorConfigStatus) DeepCopy() *DpuOperatorConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DpuOperatorConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperation) DeepCopyInto(out *ManualOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperation.
func (in *ManualOperation) DeepCopy() *ManualOperation {
	if in == nil {
		return nil
	}
	out := new(ManualOperation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManualOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperationList) DeepCopyInto(out *ManualOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManualOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperationList.
func (in *ManualOperationList) DeepCopy() *ManualOperationList {
	if in == nil {
		return nil
	}
	out := new(ManualOperationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManualOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperationReqObj) DeepCopyInto(out *ManualOperationReqObj) {
	*out = *in
	if in.NodeName != nil {
		in, out := &in.NodeName, &out.NodeName
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PciList != nil {
		in, out := &in.PciList, &out.PciList
		*out = make([]PciObj, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperationReqObj.
func (in *ManualOperationReqObj) DeepCopy() *ManualOperationReqObj {
	if in == nil {
		return nil
	}
	out := new(ManualOperationReqObj)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperationSpec) DeepCopyInto(out *ManualOperationSpec) {
	*out = *in
	in.ManualOperationReq.DeepCopyInto(&out.ManualOperationReq)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperationSpec.
func (in *ManualOperationSpec) DeepCopy() *ManualOperationSpec {
	if in == nil {
		return nil
	}
	out := new(ManualOperationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperationStatObj) DeepCopyInto(out *ManualOperationStatObj) {
	*out = *in
	if in.PciStatList != nil {
		in, out := &in.PciStatList, &out.PciStatList
		*out = make([]PciStatObj, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperationStatObj.
func (in *ManualOperationStatObj) DeepCopy() *ManualOperationStatObj {
	if in == nil {
		return nil
	}
	out := new(ManualOperationStatObj)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManualOperationStatus) DeepCopyInto(out *ManualOperationStatus) {
	*out = *in
	in.ManualOperationState.DeepCopyInto(&out.ManualOperationState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManualOperationStatus.
func (in *ManualOperationStatus) DeepCopy() *ManualOperationStatus {
	if in == nil {
		return nil
	}
	out := new(ManualOperationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkFunction) DeepCopyInto(out *NetworkFunction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkFunction.
func (in *NetworkFunction) DeepCopy() *NetworkFunction {
	if in == nil {
		return nil
	}
	out := new(NetworkFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PciObj) DeepCopyInto(out *PciObj) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PciObj.
func (in *PciObj) DeepCopy() *PciObj {
	if in == nil {
		return nil
	}
	out := new(PciObj)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PciStatObj) DeepCopyInto(out *PciStatObj) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PciStatObj.
func (in *PciStatObj) DeepCopy() *PciStatObj {
	if in == nil {
		return nil
	}
	out := new(PciStatObj)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceFunctionChain) DeepCopyInto(out *ServiceFunctionChain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceFunctionChain.
func (in *ServiceFunctionChain) DeepCopy() *ServiceFunctionChain {
	if in == nil {
		return nil
	}
	out := new(ServiceFunctionChain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceFunctionChain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceFunctionChainList) DeepCopyInto(out *ServiceFunctionChainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceFunctionChain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceFunctionChainList.
func (in *ServiceFunctionChainList) DeepCopy() *ServiceFunctionChainList {
	if in == nil {
		return nil
	}
	out := new(ServiceFunctionChainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceFunctionChainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceFunctionChainSpec) DeepCopyInto(out *ServiceFunctionChainSpec) {
	*out = *in
	if in.NetworkFunctions != nil {
		in, out := &in.NetworkFunctions, &out.NetworkFunctions
		*out = make([]NetworkFunction, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceFunctionChainSpec.
func (in *ServiceFunctionChainSpec) DeepCopy() *ServiceFunctionChainSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceFunctionChainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceFunctionChainStatus) DeepCopyInto(out *ServiceFunctionChainStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceFunctionChainStatus.
func (in *ServiceFunctionChainStatus) DeepCopy() *ServiceFunctionChainStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceFunctionChainStatus)
	in.DeepCopyInto(out)
	return out
}
