apiVersion: v1
kind: PersistentVolume
metadata:
  name: vsp-p4-pv
  namespace: {{.Namespace}}
spec:
  selector:
    app: vsp-p4
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/p4/
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{.HostName}}
