apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsp-p4-pvc
  namespace: {{.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  provisioner: kubernetes.io/no-provisioner
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-storage
