apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dpu-daemon-cluster-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - config.openshift.io
  resources:
  - dpuoperatorconfigs
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - config.openshift.io
  resources:
  - dpuoperatorconfigs/finalizers
  verbs:
  - update
