apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dpu-daemon-role-default
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch 