apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dpu-daemon
  namespace: {{.Namespace}}
spec:
  selector:
    matchLabels:
      app: dpu-daemon
  template:
    metadata:
      labels:
        app: dpu-daemon
        component: network
        type: infra
    spec:
      serviceAccountName: dpu-daemon-sa
      hostNetwork: true
      hostPID: true
      nodeSelector:
        dpu: "true"
      securityContext:
        privileged: true
      containers:
      - name: dpu-daemon
        image: {{.DpuOperatorDaemonImage}}
        securityContext:
          privileged: true
        imagePullPolicy: {{.ImagePullPolicy}}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 2
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: K8S_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: dpu-daemon-mount
          mountPath: /var/run/dpu-daemon
          mountPropagation: Bidirectional
        - name: cni-dir
          mountPath: /var/lib/cni
        - name: host-run
          mountPath: /var/run/netns
          mountPropagation: Bidirectional
        - name: proc
          mountPath: /proc
        - name: sys
          mountPath: /sys
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: dpu-daemon-mount
          hostPath:
            path: /var/run/dpu-daemon
        - name: cni-dir
          hostPath:
            path: {{.CniDir}} # /var/lib/cni
        - name: host-run
          hostPath:
            path: /var/run/netns
        - name: proc
          hostPath:
            path: /proc/
        - name: sys
          hostPath:
            path: /sys/
