# permissions for end users to view dataprocessingunits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dpu-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataprocessingunit-viewer-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - dataprocessingunits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - dataprocessingunits/status
  verbs:
  - get
