apiVersion: config.openshift.io/v1
kind: DpuOperatorConfig
metadata:
  name: dpu-operator-config
spec:
  # The operator automatically detects whether it's running on host or DPU
  # No manual mode configuration is required
  logLevel: 0
