apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default-sriov-net
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-229
  containers:
  - name: appcntr1
    image: ghcr.io/ovn-kubernetes/kubernetes-traffic-flow-tests:latest
    imagePullPolicy: Always
    securityContext:
      privileged: true
      runAsNonRoot: false
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        add: ["NET_RAW", "NET_ADMIN"]
    resources:
      requests:
        openshift.io/dpu: '1'
      limits:
        openshift.io/dpu: '1'
