apiVersion: v1
kind: Pod
metadata:
  name: nf-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: net1-nad,net1-nad,net1-nad,net1-nad,dpu-accel-nad
spec:
  nodeSelector:
    dpu.config.openshift.io/dpuside: "dpu"
  containers:
    - name: nf-container
      image: ghcr.io/ovn-kubernetes/kubernetes-traffic-flow-tests:latest
      securityContext:
        capabilities:
          add: ["NET_ADMIN", "NET_RAW"]
      resources:
        requests:
          openshift.io/dpunetwork-net1: "4"
          openshift.io/dpu-accelerated: "1"
        limits:
          openshift.io/dpunetwork-net1: "4"
          openshift.io/dpu-accelerated: "1"
